# 5: Dimensionality reduction techniques

**Part 1**

```{r}
# Libraries
library(dplyr); library(GGally);library(corrplot)

# Fetching the wrangled data
human <- read.table("data/human.txt")

glimpse(human)

ggpairs(human)

cor(human) %>% corrplot (type = "lower", tl.cex = 0.7, tl.pos="d", cl.pos="r")

ggplot(human, aes(x = Edu, y = Life)) + geom_point() + geom_smooth(method = "lm") + ggtitle("Education equals life?")

ggplot(human, aes(x = Maternal_mort, y = Life)) + geom_point() + geom_smooth(method = "lm") + ggtitle("Maternal mortality does not equal life.")

```

**Part 2**

First, we perform PCA (principal component analysis) to the unaltered data:

```{r, message=FALSE, warning=FALSE}

# PCA (with the SVD method)
pca_human1 <- prcomp(human)
summary(pca_human1)

# Biplot of the PC representation and the original variables
biplot(pca_human1, choices = 1:2, cex = c(0.8, 1), col = c("grey40", "deeppink2"))

```
The variable GNI completely dominates and explains all the variation, as its values are so huge in comparison to other variables. Thus, we need to standardize the data to get comparable results.

```{r, message=FALSE, warning=FALSE}
human_s <- scale(human)
pca_human <- prcomp(human_s)

summary(pca_human)
biplot(pca_human, choices = 1:2, cex = c(0.8, 1), col = c("grey40", "deeppink2"))

```


**Part 3**

```{r}

```

**Part 4**

```{r}

```

**Part 5**

```{r}

```

