# 6: Analysis of longitudinal data

Note: you may have to factor the categorical variables again.

```{r, warning=F, message=F}
library(dplyr); library(ggplot2); library(lme4)

# Fetching the wrangled data
data_B <- read.table("data/bprs.txt")
data_R <- read.table("data/rats.txt")

# Assigning separate ID:s for same subjects but different treatments
data_B$subject <- as.integer(data_B$subject)
data_B$id <- 
  ifelse(data_B$treatment==1,
         data_B$subject,data_B$subject+20)
unique(data_B$id)

# Factoring categorical variables again, as R interprets them as integers
data_B$treatment <- factor(data_B$treatment)
data_B$subject <- factor(data_B$subject)
data_R$ID <- factor(data_R$ID)
data_R$Group <- factor(data_R$Group)

# Glimpse of the data
glimpse(data_B)
glimpse(data_R)
summary(data_B)
summary(data_R)

```

**Part 1**

Implement the analyses of Chapter 8 of MABS using the RATS data. 

```{r}

# Boxplot to visualize the raw data
ggplot(data_R, aes(x = as.factor(Time), y = Weight, fill = Group)) + 
  geom_boxplot()

# Plots of individual rat growth profiles within their corresponding groups

ggplot(data_R, aes(x = Time, y = Weight, group = ID, col = Group)) +
  geom_line(aes(linetype = Group)) + 
  facet_grid(. ~ Group, labeller = label_both) +
  scale_x_continuous(name = "Time (days)", breaks = seq(0, 60, 10)) +
  scale_y_continuous(name = "Weight (grams)") +
  theme(legend.position = "none")

# Standardizing weight

data_R <- data_R %>%
  group_by(Time) %>%
  mutate(Weight_std = (Weight - mean(Weight))/sd(Weight) ) %>%
  ungroup()

# Plotting again with standardized weights

ggplot(data_R, aes(x = Time, y = Weight_std, group = ID, col = Group)) +
  geom_line(aes(linetype = Group)) + 
  facet_grid(. ~ Group, labeller = label_both) +
  scale_x_continuous(name = "Time (days)", breaks = seq(0, 60, 10)) +
  scale_y_continuous(name = "Standardized weight") +
  theme(legend.position = "none")

```
\
Text

$$se=\frac{sd(x)}{\sqrt{n}}$$

```{r}

# Summary data with mean and standard error of weight by group and time 
n <- data_R$Time %>% unique() %>% length()

rats_s <- data_R %>%
  group_by(Group, Time) %>%
  summarise( mean = mean(Weight), se = sd(Weight)/sqrt(n) ) %>%
  ungroup()

# Glimpse the data
glimpse(rats_s)

# Plot the mean profiles
ggplot(rats_s, aes(x = Time, y = mean, col = Group)) +
  geom_line(size=1) +
  geom_point(size=3, shape=10) +
  geom_errorbar(aes(ymin = mean - se, ymax = mean + se)) +
  scale_y_continuous(name = "mean(weight) +/- se(weight)")

```

\
Text

```{r}

# Summary dataset by treatment and subject with mean as the summary variable (ignoring baseline Time = 1).
rats_sum <- data_R %>%
  filter(Time > 1) %>%
  group_by(Group, ID) %>%
  summarise( mean=mean(Weight) ) %>%
  ungroup()

# Glimpse the data
glimpse(rats_sum)

# Draw a boxplot of the mean versus treatment
ggplot(rats_sum, aes(x = Group, y = mean)) +
  geom_boxplot() +
  stat_summary(fun = "mean", geom = "point", shape=23, size=4, fill = "white") +
  scale_y_continuous(name = "Mean weight after the start of diets")

```
\
Text

```{r}

# Creating a new dataset by filtering the three outliers 
rats_sum2 <- rats_sum %>%
  filter(ID!=2 & ID!=12 & ID!=13)  # Outlier ID's

ggplot(rats_sum2, aes(x = Group, y = mean)) +
  geom_boxplot() +
  stat_summary(fun = "mean", geom = "point", shape=23, size=4, fill = "white") +
  scale_y_continuous(name = "Mean weight after the start of diets")  
  
```
\
Text

**Part 2**

Implement the analyses of Chapter 9 of MABS using the BPRS data. 

```{r}

# Plot of BPRS scores of subjects against time, colored by treatment group

ggplot(data_B, aes(x = week, y = bprs, group = id)) +
  geom_line(aes(col = treatment)) +
  scale_x_continuous(name = "Week") +
  scale_y_continuous(name = "BPRS score") +
  theme(legend.position = "top")

# Standardizing the variable "bprs" to "bprs_std", plotting again

data_B <- data_B %>%
  group_by(week) %>%
  mutate(bprs_std = (bprs - mean(bprs))/sd(bprs) ) %>%
  ungroup()

ggplot(data_B, aes(x = week, y = bprs_std, group = id)) +
  geom_line(aes(col = treatment, linetype = treatment)) +
  scale_y_continuous(name = "Standardized BPRS score")

```
\
Text

```{r, warning=F, message=F}
# Regression model
bprs_reg <- lm(bprs ~ week + treatment, 
               data = data_B)

summary(bprs_reg)

# Random intercept model 1
bprs_ref1 <- lmer(bprs ~ week + treatment + (1 | id), 
                 data = data_B, REML = FALSE)
summary(bprs_ref1)

# Random intercept model 2
bprs_ref2 <- lmer(bprs ~ week + treatment + (week | id), 
                 data = data_B, REML = FALSE)
summary(bprs_ref2)

# Random intercept model 2
bprs_ref3 <- lmer(bprs ~ week + treatment +treatment*week + (week | id), 
                 data = data_B, REML = FALSE)
summary(bprs_ref3)

# ANOVA test on the models
anova(bprs_ref1,bprs_ref2)
anova(bprs_ref2,bprs_ref3)

```
\
Text

```{r}
# Visualization of random intercept model "bprs_ref2"
data_B$fitted2 <- fitted(bprs_ref2)

ggplot(data_B, aes(x = week, y = fitted2, group = id)) +
  geom_line(aes(col = treatment, linetype = treatment)) +
  scale_y_continuous(name = "Fitted BPRS") +
  theme(legend.position = "top")

```
\
Text
